[package]
name = "simple_app_readme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ellipsoid = {path = "../.."}

async-std = "1.12.0"
strum = { version = "0.24.1", features = ["derive"] }